// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfV1-5MOyZ8gIn6MQ_lZiXpXEjOGi2pcs',
    appId: '1:753333991622:android:40cd8a1b270c262a1d3fc7',
    messagingSenderId: '753333991622',
    projectId: 'peak-flow-91fc5',
    databaseURL: 'https://peak-flow-91fc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peak-flow-91fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtj7dJSoMCR0foEx9W2DTVaFVSNMRqeHg',
    appId: '1:753333991622:ios:b79386a9f1e221a71d3fc7',
    messagingSenderId: '753333991622',
    projectId: 'peak-flow-91fc5',
    databaseURL: 'https://peak-flow-91fc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peak-flow-91fc5.firebasestorage.app',
    iosClientId: '753333991622-a2s3c6ate3id7n6e9qk82apv6ps1bn9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.peakFlow',
  );
}
