// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1K1WaN_J_gbDZ0tJoKN6Skg8Abjyzpj8',
    appId: '1:877447504736:web:c9542f975e05744a077405',
    messagingSenderId: '877447504736',
    projectId: 'ssetup',
    authDomain: 'ssetup.firebaseapp.com',
    storageBucket: 'ssetup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGY1HlaQWJT18a-hZaHeZtwE8hGuEw4WY',
    appId: '1:877447504736:android:cdff240d3a41e9c9077405',
    messagingSenderId: '877447504736',
    projectId: 'ssetup',
    storageBucket: 'ssetup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzaS7weaftG1oD8cGOECKWp-yndLR5lfs',
    appId: '1:877447504736:ios:b3a449b624a3e7a8077405',
    messagingSenderId: '877447504736',
    projectId: 'ssetup',
    storageBucket: 'ssetup.firebasestorage.app',
    iosBundleId: 'com.example.setup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzaS7weaftG1oD8cGOECKWp-yndLR5lfs',
    appId: '1:877447504736:ios:b3a449b624a3e7a8077405',
    messagingSenderId: '877447504736',
    projectId: 'ssetup',
    storageBucket: 'ssetup.firebasestorage.app',
    iosBundleId: 'com.example.setup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1K1WaN_J_gbDZ0tJoKN6Skg8Abjyzpj8',
    appId: '1:877447504736:web:5c9214f83595d04c077405',
    messagingSenderId: '877447504736',
    projectId: 'ssetup',
    authDomain: 'ssetup.firebaseapp.com',
    storageBucket: 'ssetup.firebasestorage.app',
  );
}
