// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfV1-5MOyZ8gIn6MQ_lZiXpXEjOGi2pcs',
    appId: '1:753333991622:android:410c5f8a03197f631d3fc7',
    messagingSenderId: '753333991622',
    projectId: 'peak-flow-91fc5',
    databaseURL: 'https://peak-flow-91fc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peak-flow-91fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtj7dJSoMCR0foEx9W2DTVaFVSNMRqeHg',
    appId: '1:753333991622:ios:dc21525153d4acc91d3fc7',
    messagingSenderId: '753333991622',
    projectId: 'peak-flow-91fc5',
    databaseURL: 'https://peak-flow-91fc5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peak-flow-91fc5.firebasestorage.app',
    iosClientId: '753333991622-78f3guicd5bs8d0f9jg8jeso45pd6i79.apps.googleusercontent.com',
    iosBundleId: 'com.trywatt.watt',
  );

}